services:
  - docker:bind

stages:
  - generate
  - deploy

generate:
  stage: generate
  before_script:
    - docker login -u ${DOCKER_REGISTRY_USER_NAME} -p ${DOCKER_REGISTRY_USER_PASSWORD} registry.digiu.ai
  script:
    - export FPATH=$(echo $CI_COMMIT_TAG | cut -d '-' -f1 | tr '[:upper:]' '[:lower:]')
    - mkdir -p /var/lib/gitlab-runner/contracts/${FPATH}
    - mkdir -p /var/lib/gitlab-runner/contracts/${FPATH}/wrappers
    - cp -n ./hardhat/helper-hardhat-config.json.example /var/lib/gitlab-runner/contracts/${FPATH}/helper-hardhat-config.json
    - python .scripts/generate.py
  tags:
    - docker
  artifacts:
    paths:
      - generated-config.yml
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[A-Z]{3,15}-\d+-(deploy|wrappers)-[a-z,]{3,100}$/'

Deploy:
  stage: deploy
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[A-Z]{3,15}-\d+-(deploy|wrappers)-[a-z,]{3,100}$/'
