services:
  - docker:bind

stages:
  - generate
  - deploy

generate:
  stage: generate
  before_script:
    - docker login -u ${DOCKER_REGISTRY_USER_NAME} -p ${DOCKER_REGISTRY_USER_PASSWORD} registry.digiu.ai
  script:
    - export ACTION=$(echo $CI_COMMIT_TAG | cut -d '-' -f3)
    - export NETWORKS=$(echo $CI_COMMIT_TAG | cut -d '-' -f4)
    - if [[ "$ACTION" == "deploy" ]]; then export ACTION="eth-testnet-migrate"; fi
    - if [[ "$NETWORKS" == "all" ]]; then export NETWORKS=${DEFAULT_NETWORKS}; fi
    - echo "it will be launched $ACTION"
    - echo "for this networks $NETWORKS"
    - python .scripts/generate.py
  tags:
    - docker
  artifacts:
    paths:
      - generated-config.yml
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[A-Z]{3,15}-\d+-(deploy|wrappers)-[a-z,]{3,100}$/'

Deploy:
  stage: deploy
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[A-Z]{3,15}-\d+-(deploy|wrappers)-[a-z,]{3,100}$/'
