services:
  - docker:bind

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - docker login -u ${DOCKER_REGISTRY_USER_NAME} -p ${DOCKER_REGISTRY_USER_PASSWORD} registry.digiu.ai
  script:
    - export ACTION=$(echo $CI_COMMIT_TAG | cut -d '-' -f3)
    - if [[ "$ACTION" == "deploy" ]]; then export ACTION="eth-testnet-migrate"; echo "$ACTION"; elif [[ "$ACTION" == "wrappers" ]];then echo "$ACTION"; fi
    - export NETWORKS=$(echo $CI_COMMIT_TAG | cut -d '-' -f4)
    - if [[ "$NETWORKS" == "all" ]]; then export NETWORKS=${DEFAULT_NETWORKS}; fi
    - echo "$NETWORKS"
    - if [[ "$ACTION" == "wrappers" ]]; then export RUN="wrappers"; else export RUN="$ACTION $NETWORKS"; fi
    - echo "$RUN"
    - echo "$ACTION"
    - echo "$NETWORKS"
#    - docker run -t --rm -v $(pwd):/app --user builder --add-host=mumbai.testnet.eywa.fi:10.1.0.21 --add-host=huobi.testnet.eywa.fi:10.1.0.21 --add-host=rinkeby.testnet.eywa.fi:10.1.0.21 --add-host=bsc.testnet.eywa.fi:10.1.0.21 registry.digiu.ai/base/eywa-contracts:2 make -C /app "$ACTION" "$NETWORKS"
  tags:
    - docker
  artifacts:
    paths:
        - wrappers/
        - hardhat/helper-hardhat-config.json
        - hardhat/.env
        - hardhat/networks_env
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[A-Z]{3,15}-\d+-(deploy|wrappers)-[a-z,]{3,50}$/'
      when: manual
