/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPortal, IPortalInterface } from "../IPortal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "address",
        name: "_receiveSide",
        type: "address",
      },
      {
        internalType: "address",
        name: "_oppositeBridge",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_chainID",
        type: "uint256",
      },
    ],
    name: "synthesize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPortal__factory {
  static readonly abi = _abi;
  static createInterface(): IPortalInterface {
    return new utils.Interface(_abi) as IPortalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPortal {
    return new Contract(address, _abi, signerOrProvider) as IPortal;
  }
}
