/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IPortalInterface extends utils.Interface {
  functions: {
    "synthesize(address,uint256,address,address,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "synthesize",
    values: [string, BigNumberish, string, string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "synthesize", data: BytesLike): Result;

  events: {};
}

export interface IPortal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPortalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    synthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "synthesize(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  synthesize(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "synthesize(address,uint256,address,address,address,address,uint256)"(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    synthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "synthesize(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    synthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "synthesize(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    synthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "synthesize(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
