/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type DelegatedCallReceiptStruct = {
  executionPrice: BigNumberish;
  timeout: BigNumberish;
  v: [BigNumberish, BigNumberish];
  r: [BytesLike, BytesLike];
  s: [BytesLike, BytesLike];
};

export type DelegatedCallReceiptStructOutput = [
  BigNumber,
  BigNumber,
  [number, number],
  [string, string],
  [string, string]
] & {
  executionPrice: BigNumber;
  timeout: BigNumber;
  v: [number, number];
  r: [string, string];
  s: [string, string];
};

export interface RouterInterface extends utils.Interface {
  functions: {
    "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))": FunctionFragment;
    "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)": FunctionFragment;
    "pusher(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "delegatedTokenSynthesize",
    values: [
      string,
      BigNumberish,
      string,
      string,
      string,
      string,
      BigNumberish,
      DelegatedCallReceiptStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "delegatedTokenSynthesize1",
    values: [string, BigNumberish, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pusher", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "delegatedTokenSynthesize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegatedTokenSynthesize1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pusher", data: BytesLike): Result;

  events: {
    "PaymentEvent(address,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PaymentEvent"): EventFragment;
}

export type PaymentEventEvent = TypedEvent<
  [string, string, BigNumber, string],
  {
    userFrom: string;
    payToken: string;
    executionPrice: BigNumber;
    worker: string;
  }
>;

export type PaymentEventEventFilter = TypedEventFilter<PaymentEventEvent>;

export interface Router extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    delegatedTokenSynthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    delegatedTokenSynthesize1(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pusher(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "pusher(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  delegatedTokenSynthesize(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    _receipt: DelegatedCallReceiptStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))"(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    _receipt: DelegatedCallReceiptStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  delegatedTokenSynthesize1(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)"(
    _token: string,
    _amount: BigNumberish,
    _from: string,
    _to: string,
    _receiveSide: string,
    _oppositeBridge: string,
    _chainID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pusher(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "pusher(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    delegatedTokenSynthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    delegatedTokenSynthesize1(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pusher(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "pusher(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "PaymentEvent(address,address,uint256,address)"(
      userFrom?: string | null,
      payToken?: null,
      executionPrice?: null,
      worker?: string | null
    ): PaymentEventEventFilter;
    PaymentEvent(
      userFrom?: string | null,
      payToken?: null,
      executionPrice?: null,
      worker?: string | null
    ): PaymentEventEventFilter;
  };

  estimateGas: {
    delegatedTokenSynthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    delegatedTokenSynthesize1(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pusher(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pusher(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    delegatedTokenSynthesize(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "delegatedTokenSynthesize(address,uint256,address,address,address,address,uint256,(uint256,uint256,uint8[2],bytes32[2],bytes32[2]))"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      _receipt: DelegatedCallReceiptStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    delegatedTokenSynthesize1(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "delegatedTokenSynthesize1(address,uint256,address,address,address,address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      _from: string,
      _to: string,
      _receiveSide: string,
      _oppositeBridge: string,
      _chainID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pusher(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pusher(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
